controller_manager_ns: moveit_simple_controller_manager
controller_list:

  - name: kuka_lwr
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - kuka_joint_1
      - kuka_joint_2
      - kuka_joint_3
      - kuka_joint_4
      - kuka_joint_5
      - kuka_joint_6
      - kuka_joint_7
 
